# Site settings
title: Apexure
description: "Apexure Software Solutions"
baseurl: "" 
url: "http://jatinderapex.github.io/" 
tagline: "Apexure Software Solutions"

# Build settings
markdown: kramdown

highlighter: rouge
